name: Push Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
    paths:
      - "typescript/**"

permissions:
  contents: read

jobs:
  security-checks:
    uses: ./.github/workflows/ts-run-security-checks.yml
    secrets: inherit